name: mech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.2.0  
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  
  # Firebase packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  
  # OTP field package
  pinput: ^6.0.1 

  google_sign_in: ^7.2.0 
  geolocator: ^14.0.2 
  shared_preferences: ^2.5.1
  
  # Google Maps integration ke liye 
  google_maps_flutter: ^2.5.3
  location: ^8.0.1
  latlong2: ^0.8.1
  url_launcher: ^6.3.1
  shimmer: ^3.0.0

  # Cupertino Icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Bold.ttf
          weight: 700